### ISSUE TITLE
Name abuse

### ISSUE THREAD

**Issue by spixi** [ProjectIxian/Spixi#1]
Dear Sirs/Madams,

I hereby request the deletion of this project, because it violates my name rights. I registered the user name spixi on GitHub on January 2013. Naming your project spixi brings my name in relationship with cryptomining software, which I don't support. The name spixi is derived by my surname Spix.

If the project has not been deleted until 26 May 2020, I feel compelled to take legal action.

Best regards

Marius Spix

**Comment by nakizjong** [comment]
Ah yes, might I suggest a new name?
How about Fully Uncentralized Chat Klient SPIXI?

**Comment by hooftly** [comment]
@spixi any legal action you take will be a waste of time.  You do not own a trademark on the name spixi therefore have no naming rights here.  I suggest you change your username if it bothers you so much.  Or go to court and pay yours and the projects legal bills when you lose.

**Comment by Rexoflex** [comment]
> 
> 
> Dear Sirs/Madams,
> 
> I hereby request the deletion of this project, because it violates my name rights. I registered the user name spixi on GitHub on January 2013. Naming your project spixi brings my name in relationship with cryptomining software, which I don't support. The name spixi is derived by my surname Spix.
> 
> If the project has not been deleted until 26 May 2020, I feel compelled to take legal action.
> 
> Best regards
> 
> Marius Spix

Dear Mr. Spix (@spixi ),

We have received your complaint regarding the name of our app - Spixi.

We understand that you have registered on Github the user name “spixi”, for which you do not own any naming rights. Our project does not in any way, shape or form relate to your user name or last name like you claim. Furthermore, we have not named our software “Marius Spix”, which would give you a reasonable cause for concern. 

Our decision to name our app Spixi was a result of a deliberate process and is a portmanteau of the words “Speak” and “Ixian”.

Additionally, the word “spixi” is used to describe other things that you are also not affiliated with, such as the Spixi Snail, Leptodactylus spixi, Synallaxis spixi, etc.

Having stated that, we have to decline your request to delete this project.

If you have any additional questions, feel free to contact us directly.


With best regards,
Team Ixian

**Comment by spixi** [comment]
> 
> 
> > Dear Sirs/Madams,
> > I hereby request the deletion of this project, because it violates my name rights. I registered the user name spixi on GitHub on January 2013. Naming your project spixi brings my name in relationship with cryptomining software, which I don't support. The name spixi is derived by my surname Spix.
> > If the project has not been deleted until 26 May 2020, I feel compelled to take legal action.
> > Best regards
> > Marius Spix
> 
> Dear Mr. Spix (@spixi ),
> 
> We have received your complaint regarding the name of our app - Spixi.
> 
> We understand that you have registered on Github the user name “spixi”, for which you do not own any naming rights. Our project does not in any way, shape or form relate to your user name or last name like you claim. Furthermore, we have not named our software “Marius Spix”, which would give you a reasonable cause for concern.
> 
> Our decision to name our app Spixi was a result of a deliberate process and is a portmanteau of the words “Speak” and “Ixian”.
> 
> Additionally, the word “spixi” is used to describe other things that you are also not affiliated with, such as the Spixi Snail, Leptodactylus spixi, Synallaxis spixi, etc.
> 
> Having stated that, we have to decline your request to delete this project.
> 
> If you have any additional questions, feel free to contact us directly.
> 
> With best regards,
> Team Ixian

Dear @Rexoflex,

thank you for your reply.

I cannot follow your argumentation. Explaining a name with a portmanteau is comprehensible, but not sufficient. One could argue, that their project “Microsoft” is a portmanteau of “microbe” and “softball”, but that does not make that name publicly available.

Also the argument with the mentioned animal species cannot be understood. For example, there is also the Zebra Apple Snail (Asolene spixii), and yet you cannot simply call your project Apple, because that name is already in use.

It is very well to make mistakes, but I cannot tolerate this use of my name.  Crypto currencies are a new area of great legal uncertainty and there are many cases of fraud involving crypto currencies. Without accusing Ixian or the Spixi project of anything, I unfortunately cannot tolerate my name being used for such a project.

Therefore I recommend to delete the project immediately to avoid legal disputes. 

Sincerely

Marius Spix

**Comment by hooftly** [comment]
> > > Dear Sirs/Madams,
> > > I hereby request the deletion of this project, because it violates my name rights. I registered the user name spixi on GitHub on January 2013. Naming your project spixi brings my name in relationship with cryptomining software, which I don't support. The name spixi is derived by my surname Spix.
> > > If the project has not been deleted until 26 May 2020, I feel compelled to take legal action.
> > > Best regards
> > > Marius Spix
> > 
> > 
> > Dear Mr. Spix (@spixi ),
> > We have received your complaint regarding the name of our app - Spixi.
> > We understand that you have registered on Github the user name “spixi”, for which you do not own any naming rights. Our project does not in any way, shape or form relate to your user name or last name like you claim. Furthermore, we have not named our software “Marius Spix”, which would give you a reasonable cause for concern.
> > Our decision to name our app Spixi was a result of a deliberate process and is a portmanteau of the words “Speak” and “Ixian”.
> > Additionally, the word “spixi” is used to describe other things that you are also not affiliated with, such as the Spixi Snail, Leptodactylus spixi, Synallaxis spixi, etc.
> > Having stated that, we have to decline your request to delete this project.
> > If you have any additional questions, feel free to contact us directly.
> > With best regards,
> > Team Ixian
> 
> Dear @Rexoflex,
> 
> thank you for your reply.
> 
> I cannot follow your argumentation. Explaining a name with a portmanteau is comprehensible, but not sufficient. One could argue, that their project “Microsoft” is a portmanteau of “microbe” and “softball”, but that does not make that name publicly available.
> 
> Also the argument with the mentioned animal species cannot be understood. For example, there is also the Zebra Apple Snail (Asolene spixii), and yet you cannot simply call your project Apple, because that name is already in use.
> 
> It is very well to make mistakes, but I cannot tolerate this use of my name. Crypto currencies are a new area of great legal uncertainty and there are many cases of fraud involving crypto currencies. Without accusing Ixian or the Spixi project of anything, I unfortunately cannot tolerate my name being used for such a project.
> 
> Therefore I recommend to delete the project immediately to avoid legal disputes.
> 
> Sincerely
> 
> Marius Spix

No, one could not claim that about Microsoft because they own trademark rights to that name and retain all naming rights to said name.

This issue should be marked as spam and closed.  

You have no legal legs to stand on here.

Perhaps Ixian should contact Github and request your username be changed because as far as I know they have begun the trademark process for the name spixi.

**Comment by spixi** [comment]
> 
> 
> > > > Dear Sirs/Madams,
> > > > I hereby request the deletion of this project, because it violates my name rights. I registered the user name spixi on GitHub on January 2013. Naming your project spixi brings my name in relationship with cryptomining software, which I don't support. The name spixi is derived by my surname Spix.
> > > > If the project has not been deleted until 26 May 2020, I feel compelled to take legal action.
> > > > Best regards
> > > > Marius Spix
> > > 
> > > 
> > > Dear Mr. Spix (@spixi ),
> > > We have received your complaint regarding the name of our app - Spixi.
> > > We understand that you have registered on Github the user name “spixi”, for which you do not own any naming rights. Our project does not in any way, shape or form relate to your user name or last name like you claim. Furthermore, we have not named our software “Marius Spix”, which would give you a reasonable cause for concern.
> > > Our decision to name our app Spixi was a result of a deliberate process and is a portmanteau of the words “Speak” and “Ixian”.
> > > Additionally, the word “spixi” is used to describe other things that you are also not affiliated with, such as the Spixi Snail, Leptodactylus spixi, Synallaxis spixi, etc.
> > > Having stated that, we have to decline your request to delete this project.
> > > If you have any additional questions, feel free to contact us directly.
> > > With best regards,
> > > Team Ixian
> > 
> > 
> > Dear @Rexoflex,
> > thank you for your reply.
> > I cannot follow your argumentation. Explaining a name with a portmanteau is comprehensible, but not sufficient. One could argue, that their project “Microsoft” is a portmanteau of “microbe” and “softball”, but that does not make that name publicly available.
> > Also the argument with the mentioned animal species cannot be understood. For example, there is also the Zebra Apple Snail (Asolene spixii), and yet you cannot simply call your project Apple, because that name is already in use.
> > It is very well to make mistakes, but I cannot tolerate this use of my name. Crypto currencies are a new area of great legal uncertainty and there are many cases of fraud involving crypto currencies. Without accusing Ixian or the Spixi project of anything, I unfortunately cannot tolerate my name being used for such a project.
> > Therefore I recommend to delete the project immediately to avoid legal disputes.
> > Sincerely
> > Marius Spix
> 
> No, one could not claim that about Microsoft because they own trademark rights to that name and retain all naming rights to said name.
> 
> This issue should be marked as spam and closed.
> 
> You have no legal legs to stand on here.
> 
> Perhaps Ixian should contact Github and request your username be changed because as far as I know they have begun the trademark process for the name spixi.

You may try it. What a coincidence, the US trademark SPIXI which was owned by Escargot LLC has been cancelled on March 27, 2020.

**Comment by leahcornelius** [comment]
You do also understand that this is a distributed, immutable ledger right? You can’t just delete it. It doesn’t work like that...

**Comment by spixi** [comment]
@leocornelius That is not my problem. You can recall and extinguish all storage media containing that software.

**Comment by leahcornelius** [comment]
You clearly show a sincere lack of understanding as to what the ramifications of trying to “delete a cryptocurrency” are. It’s no small feat. That combined with your ludicrous reason as to why you have any legal ground to do anything about it make me surprised this issue is still open

**Comment by leahcornelius** [comment]
My name is Leo. Does that mean I can sue any company that uses the word Leo in their name? 😂😂

**Comment by spixi** [comment]
@leocornelius, what would you do, if someone sells a dubious product called Leo Cornelius and abuses your name for fraudelent activities?

It does not matter how many it would cost. Unauthorized use is unauthorized use. Courts make no difference there.

**Comment by Splxl** [comment]
Dude, this is probably the worst attempt at extorting money that ive ever seen.
No one care if your name is Spixi or anything like that, it doesnt even matter.
It not related in any way or form to the Ixian product.
You cant ''own'' a generic name like that , your argument make no sense at all.
There's literally at most 0% chance that you would win in court, even a dollars.
Any judge or lawyer will laught at you and make you pay money for losing on top of it.
I mean if you truely had a chance to win anything in court you wouldnt complain on github like a slowpoke, instead you would shut up and send some legal paper to the Ixian Team.
You so annoying that If I was the Ixian Team I would definitly sue your ass for extorsion.
So yeah, you can still leave like a real man while you can or continue to complain with your absolutely delusional statement .

**Comment by leahcornelius** [comment]
> @leocornelius, what would you do, if someone sells a dubious product called Leo Cornelius and abuses your name for fraudelent activities?
> 
> It does not matter how many it would cost. Unauthorized use is unauthorized use. Courts make no difference there.

Your joking right? You seriously think the courts would listen to you? You don’t own the name spixi. I right now could go and launch a product named spixi. You can’t do anything about it- just like you could go and launch a company named Leo. Stop this nonsensical babble before you get reported for exortion or harassment. Pathetic

**Comment by leahcornelius** [comment]
Also this project is fraudulent or dubious. So so far you’ve proved a grand total of 0 valid points. Why this issue is still open and not locked is beond me

**Comment by AyzeLYC** [comment]
> @leocornelius, what would you do, if someone sells a dubious product called Leo Cornelius and abuses your name for fraudelent activities?
> 
> It does not matter how many it would cost. Unauthorized use is unauthorized use. Courts make no difference there.

You can't try to delete a github repository only because the repository name begin by spixi, you don't own the Spixi word.

This is not because your family name is spixi or another thing you can delete this project.

And what are your valid points, for the moment we don't see any valid points.

Now if you don't have any valid points, shut up and don't try to delete this repository.

**Comment by angryolk** [comment]
so base on your comment i am going to sue Apple. because the company Apple has been abused my Name. and i will win obviously, thank you  i will be trillionaire. .

**Comment by leahcornelius** [comment]
https://www.leo-pharma.co.uk/ these people are GOING DOWN!!! @spixi thanks for the life advicde. im gonna sue every company with the word leo in!!

**Comment by angryolk** [comment]
also, MR spixi, if you have common sense, SPIXI is not a unique name in the world, this word was not created by you and for you. you will find another person on the earth has the exactly same name with you,  maybe he is a celebrity maybe he is a criminal. do you think you are getting any benefit or bad on having  same name from both of them? do you think the celebrity will sue you because you are using the same name as him and you are potentially outbreach his name? the answer is No! he does not care, because the name and the image needs to be match!  do you think that you will in jail because you are using the same name of that criminal? the answer is NO! because your face is entirely different from that criminal. you would better to sue the people who has the same name as you, and leave this project free.

**Comment by Rexoflex** [comment]
> 
> 
> > > Dear Sirs/Madams,
> > > I hereby request the deletion of this project, because it violates my name rights. I registered the user name spixi on GitHub on January 2013. Naming your project spixi brings my name in relationship with cryptomining software, which I don't support. The name spixi is derived by my surname Spix.
> > > If the project has not been deleted until 26 May 2020, I feel compelled to take legal action.
> > > Best regards
> > > Marius Spix
> > 
> > 
> > Dear Mr. Spix (@spixi ),
> > We have received your complaint regarding the name of our app - Spixi.
> > We understand that you have registered on Github the user name “spixi”, for which you do not own any naming rights. Our project does not in any way, shape or form relate to your user name or last name like you claim. Furthermore, we have not named our software “Marius Spix”, which would give you a reasonable cause for concern.
> > Our decision to name our app Spixi was a result of a deliberate process and is a portmanteau of the words “Speak” and “Ixian”.
> > Additionally, the word “spixi” is used to describe other things that you are also not affiliated with, such as the Spixi Snail, Leptodactylus spixi, Synallaxis spixi, etc.
> > Having stated that, we have to decline your request to delete this project.
> > If you have any additional questions, feel free to contact us directly.
> > With best regards,
> > Team Ixian
> 
> Dear @Rexoflex,
> 
> thank you for your reply.
> 
> I cannot follow your argumentation. Explaining a name with a portmanteau is comprehensible, but not sufficient. One could argue, that their project “Microsoft” is a portmanteau of “microbe” and “softball”, but that does not make that name publicly available.
> 
> Also the argument with the mentioned animal species cannot be understood. For example, there is also the Zebra Apple Snail (Asolene spixii), and yet you cannot simply call your project Apple, because that name is already in use.
> 
> It is very well to make mistakes, but I cannot tolerate this use of my name. Crypto currencies are a new area of great legal uncertainty and there are many cases of fraud involving crypto currencies. Without accusing Ixian or the Spixi project of anything, I unfortunately cannot tolerate my name being used for such a project.
> 
> Therefore I recommend to delete the project immediately to avoid legal disputes.
> 
> Sincerely
> 
> Marius Spix



> 
> 
> @leocornelius, what would you do, if someone sells a dubious product called Leo Cornelius and abuses your name for fraudelent activities?
> 
> It does not matter how many it would cost. Unauthorized use is unauthorized use. Courts make no difference there.

Dear Mr. Marius Spix (@spixi )

We have to reaffirm our statement that our project Spixi does not in any way, shape or form relate to your name.

We would like to point out the following:

1. We have not named the project “Marius Spix”, which would give you a reasonable cause for concern. So it is safe to say that we have not used your name.

2. We agree that the name “Spixi” is not freely available, as we have registered the trademark “Spixi” along with the graphical representation at the EUIPO.

3. While developing this project, we have taken every precaution in order to follow any and all known regulations in this field. 

4. We are not “selling” anything, let alone a “dubious” product as you called it. We have not asked anyone for money. Our software is entirely open source, and as such available for free.

5. We are not abusing your name in any way, even less so for “fraudulent activities” like you claim.

A number of your statements are untrue, unsubstantiated and slandering, which might cause damage to our brand. Therefore, we are closing this issue and reporting the abuse to Github.

Team Ixian

**Comment by spixi** [comment]
For clarification: I never accuse this particular project as fraudulent, but many activities involving cryptocurrencies are.

**Comment by leahcornelius** [comment]
Once again showing a sincere lack of understanding in the cryptospace. Fuck
off and go and extort someone’s else

**Comment by spixi** [comment]
> Once again showing a sincere lack of understanding in the cryptospace. Fuck off and go and extort someone’s else

Serious? You are half as old as me. I am a professional software consultant developing business applications for SAP systems and not a scriptkiddie. Cryptocurrencies are a Ponzi scheme like the South Sea Company.

**Comment by leahcornelius** [comment]
And yet somehow I am wielding far greater logic.

**Comment by feberschnee** [comment]
Don't get trolled by the user spixi. He can't help himself other than threaten, dox and stalk people if he feels like it. 
Usually he freaks out whenever he thinks his name is used in an unfavorable way.
This lunatic has done the same thing on Wikipedia, Mumble and 4Chan.
But he kept coming back to all of these communities and fueled the hatred against him by doxing, threatening and stalking.

However you all should be aware that he might use your real life in informations and create fake accounts to slander your names (because he feels entitled to it after you "slandered" his name with this project).

Nevertheless he has become a lolcow in the german speaking community on 4chan's international board:
https://boards.4channel.org/int/catalog#s=deutsch

For our lolcow collection of him - please visit:
https://imgur.com/a/zZRrq7K
https://imgur.com/a/hhnJ2U1

By the way Leo Cornelius you are our hero for wiping the floor with this 27 yo assburger virgin.

**Comment by Tuxchen** [comment]
@feberschnee 
Oh my God, this is absolutly underrated :D
