### ISSUE TITLE
Language Settings

### ISSUE THREAD

**Issue by aaveu** [ProjectIxian/Spixi#2]
Can You add Chinese language and Arabic language

**Comment by AyzeLYC** [comment]
> Can You add Chinese language and Arabic language

Hi aveu722, for the moment the Spixi app is on development, but the Chinese language will be added soon ( you can look here at the languages who will be added soon : https://www.figma.com/proto/V3Pghe7gid9rW9QT18yH2f/Spixi-Onboarding?node-id=1%3A2&viewport=-749%2C367%2C0.6113330721855164&scaling=scale-down )

If you want, you can send your propositions in the channel #feature-suggestion in the Official Discord Server ( link : https://discord.gg/P493UN9 )

**Comment by AyzeLYC** [comment]
If you don't get other questions or ideas, the Issue will be closed
