### ISSUE TITLE
Notifications on android without google services 

### ISSUE THREAD

**Issue by gitbq** [ProjectIxian/Spixi#20]
Great work on this app!! I really appreciate the language change method. It’s fast and smooth and easy.

I live in an area where Google services are not common on many android devices. The problem is: on an android phone, if the Spixi app is not open in the background it will not receive notification that a message has been received.

is it possible to support an alternate notification method so even phones without Google services can receive notifications and get the full benefit from this potentially great messaging tool?

Signal has its own notification system that works seamlessly on these android devices. As signal is open source, is there any way to implement the alternative notification system they use into the android version of spixi?

**Comment by Rexoflex** [comment]
Hello @gitbq thank you for opening this issue. We will take review this and see how we could approach it. We will keep you posted!
